# Generated by Django 4.1.4 on 2022-12-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconf",
            name="docker_image_url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appconf",
            name="num_replicas",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
