# Generated by Django 4.1.4 on 2022-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_appconf_docker_image_url_appconf_num_replicas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appconf",
            old_name="num_replicas",
            new_name="num_replicas_max",
        ),
        migrations.AddField(
            model_name="appconf",
            name="num_replicas_min",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
