# Generated by Django 4.1.4 on 2022-12-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_num_replicas_appconf_num_replicas_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconf",
            name="current_instances",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
