# Generated by Django 4.1.4 on 2022-12-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_appconf_current_instances"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconf",
            name="port",
            field=models.TextField(default=9090),
            preserve_default=False,
        ),
    ]
