# Generated by Django 4.1.4 on 2022-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_appconf_port"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="config",
        ),
        migrations.AddField(
            model_name="application",
            name="current_instances",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="num_replicas_max",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="num_replicas_min",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="port",
            field=models.TextField(default=7654),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AppConf",
        ),
    ]
