# Generated by Django 4.1.4 on 2022-12-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_application_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
