# Generated by Django 4.1.4 on 2022-12-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_application_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="id",
            new_name="_id",
        ),
    ]
